# Generated by Django 3.2.9 on 2021-11-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spilled_bits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug_add',
            field=models.CharField(default='2021-11-15 06:02:28.696388', max_length=30),
        ),
    ]
