# Generated by Django 3.2.9 on 2021-11-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spilled_bits', '0002_article_slug_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug_add',
            field=models.CharField(default='2021-11-15 06:10:33.903140', editable=False, max_length=30),
        ),
    ]
