# Generated by Django 3.2.9 on 2021-11-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spilled_bits', '0003_alter_article_slug_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug_add',
        ),
        migrations.AddField(
            model_name='article',
            name='filler',
            field=models.CharField(default='2021-11-15 06:13:37.364634', editable=False, max_length=30),
        ),
    ]
