# Generated by Django 3.2.9 on 2021-11-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spilled_bits', '0004_auto_20211115_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='filler',
            field=models.CharField(default='2021-11-15 06:21:45.107531', max_length=30),
        ),
    ]
