# Generated by Django 3.2.9 on 2021-11-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spilled_bits', '0005_alter_article_filler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='filler',
            field=models.CharField(default='2021-11-15 06:22:27.387949', max_length=30),
        ),
    ]
