# Generated by Django 3.2.9 on 2021-11-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spilled_bits', '0007_auto_20211115_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='filler',
            field=models.CharField(default='2021-11-15 06:47:41.451549', max_length=30),
        ),
    ]
