# Generated by Django 3.2.9 on 2021-11-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spilled_bits', '0009_alter_article_filler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='filler',
            field=models.CharField(default='2021-11-15 06:48:39.859890', max_length=30),
        ),
    ]
