# Generated by Django 3.2.9 on 2021-11-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spilled_bits', '0016_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('Publish', 'Publish'), ('Private', 'Private')], max_length=15, null=True),
        ),
    ]
